name: Firebase Hosting Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
      
      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Build project
        run: npm run build:prod

      - name: Set up Google Cloud credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcloud-service-key.json

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-service-key.json
        run: |
          # Authenticate with Google Cloud using the service account
          gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
          
          # Set the project ID for Google Cloud
          gcloud config set project ${{ secrets.GCLOUD_PROJECT_ID }}
          
          # Deploy to Firebase Hosting
          npx firebase deploy --only hosting --debug


# name: Firebase Hosting Deployment

# on:
#   push:
#     branches:
#       - main  # Men-trigger workflow setiap ada push ke branch `main`
#   pull_request:
#     branches:
#       - main  # Men-trigger workflow setiap ada pull request ke branch `main`

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Install Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '22'  # Pastikan menggunakan versi Node.js yang sesuai dengan proyek Anda

#       - name: Install dependencies
#         run: npm install

#       - name: Build project
#         run: npm run build:prod  # Sesuaikan dengan script build yang ada di package.json Anda

#       - name: Deploy to Firebase Hosting
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#         run: |
#           npm install -g firebase-tools
#           firebase deploy --only hosting --token $FIREBASE_TOKEN --debug

